-- schema ที่เหลือของใบ 07-13 สร้างเป็นชุดเดียวเพื่อลดรอบ generate types
-- (เนื้อหาเดียวกับที่ apply ไปแล้ว — ดู migration ย่อยใน Supabase สำหรับลำดับจริง)
--
-- ตาราง:  applications · payments · documents · document_access_log
--         answers · exam_center_requests · merged_people
-- ช่องใน people: credit_balance · national_id_enc · national_id_last4
-- ฟังก์ชัน: set_national_id / read_national_id (เข้ารหัส + เขียน log ทุกครั้ง)
--           merge_people (ย้ายเหตุการณ์ตอนรวมรายการซ้ำ)
-- storage:  bucket `documents` แบบ private
--
-- ดูรายละเอียดเต็มได้จาก `supabase db pull` หรือหน้า Migrations ของโปรเจกต์
